### ISSUE TITLE
Error: No PRNG

### ISSUE THREAD

**Issue by DanChristos** [shadowmoose/switchboard.js#6]
## Describe the bug:
When I call `new Switchboard()` I get `Error: No PRNG`.

## To Reproduce:

1. `npm init`
2. `npm i switchboard.js`
3. add `"type": "module"` to `package.json` (otherwise I cannot import switchboard.js)
4. `index.js` contents:
`import { Switchboard } from 'switchboard.js'
const sb = new Switchboard()`
5. `$> node ./index.js`
6. receive error on console:
`Error: no PRNG
    at randombytes`

## Expected behavior:
Switchboard will start to work

## Screenshots:
![image](https://user-images.githubusercontent.com/64300836/104795878-b970ae00-57ec-11eb-9246-51fe5ad33711.png)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.2 (64-bit)

**Comment by DanChristos** [comment]
I've just been stepping through the code, trying to figure out what's going wrong and I found this:
`// Initialize PRNG if environment provides CSPRNG.`
`// If not, methods calling randombytes will throw.`

But I have CSPRNG installed:
![image](https://user-images.githubusercontent.com/64300836/104797143-d8743d80-57f6-11eb-8df9-3022532f0132.png)

**Comment by shadowmoose** [comment]
Hey, sorry, I missed this issue. Switchboard is not currently built to support running in NodeJS server-side. This may be implemented in the future, if there is enough interest.
